### ISSUE TITLE
Percentage speed change doesn't work

### ISSUE THREAD

**Issue by zombozo12** [MillhioreF/MapSpeedChanger#1]
Speed change with percentage doesn't work. Just it. I was input 110% and the output said 110 BPM. lol xD

I've tried to solve the problem, but I can't find it. But I'm 100% sure it's the Boolean fault. The logic is wrong, but I can't solve it :( 

Have u tried ur program by yourself?

**Comment by MillhioreF** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa I'm so sorry,  forgot I even had this on github. The program doesn't even work any more on map versions over v9. Please find another speed changer.

**Comment by zombozo12** [comment]
nonono, it's work when I use BPM input speed but doesn't work with percentage input..
